version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Install dependencies needed for running tests
      - echo Installing dependencies
      - pip install -r src/try_django/requirements.txt

  build:
    commands:
      - echo Build started on `date`
      - echo Running tests
      - python3 src/try_django/manage.py test

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'